# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Extract tag name
        id: extract_tag
        run: |
          echo "TAG_NAME=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
          echo "TAG_NAME=$(echo $GITHUB_REF | cut -d '/' -f 3)"      

      - name: Build yami-shop-admin
        run: |
          ls -rt
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          cd yami-shop-admin
          ls -rt
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/chenzhsh/yami-shop-admin:${{ env.TAG_NAME }}
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/chenzhsh/yami-shop-admin:${{ env.TAG_NAME }}

      - name: Build yami-shop-api
        run: |
          ls -rt
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          cd yami-shop-api
          ls -rt
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/chenzhsh/yami-shop-api:${{ env.TAG_NAME }}
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/chenzhsh/yami-shop-api:${{ env.TAG_NAME }}
