# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract tag name
        id: extract_tag
        run: |
          echo "TAG_NAME=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
          echo "TAG_NAME=$(echo $GITHUB_REF | cut -d '/' -f 3)" 

      - name: build and push image
        uses: docker/build-push-action@v2
        with:
          context: front-end/mall4v
          push: true
          tags: cxyjerry/pilipala-web:${{ env.TAG_NAME }}

      - name: login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
